"""In-app "How to Use" guide: quick start, what every screen means, the 8
sample scenarios explained, and an FAQ. Written for a first-time visitor with
zero prior context on this project (a hiring manager, not a developer).
"""
from __future__ import annotations

import streamlit as st

from revops_copilot import ui_theme

st.set_page_config(page_title="How to Use — RevOps Copilot", layout="wide")
ui_theme.inject()

st.title("How to Use This Demo")
st.caption(
    "A plain-language guide to what this app does and how to get the most out of it "
    "in under two minutes."
)

st.markdown(
    ui_theme.note(
        "<strong>Quick start:</strong> go to the <strong>app</strong> page in the sidebar, "
        "pick a sample lead from the dropdown, and click <strong>Run Copilot</strong>. "
        "That's it — everything else on this page is optional depth for anyone who wants it.",
        "ae",
    ),
    unsafe_allow_html=True,
)

st.header("What this is")
st.write(
    "This is a working simulation of an AI-assisted revenue-operations workflow: an inbound "
    "sales lead or RFP comes in, and the system automatically checks the data for problems, "
    "enriches it with firmographic context, scores and routes it, drafts a rep brief and "
    "follow-up email, and — for RFPs — drafts a proposal. Every run is recorded so the "
    "**Metrics Dashboard** page can show the aggregate business impact."
)
st.write(
    "It runs in **Mock / Template Mode** by default, meaning every result comes from "
    "deterministic, rule-based logic — no API key, no network calls, no cost, and the exact "
    "same output every time you run the same scenario. If a real Anthropic API key is "
    "configured, it switches to **Live Claude Mode** and the rep brief, email, and proposal "
    "text are generated by Claude instead of a template."
)

st.header("The main screen, step by step")
st.write(
    "When you click **Run Copilot**, up to nine steps appear in order. Click any step's "
    "header to expand it and see the detail behind that step."
)

steps = [
    ("1. Lead Intake", "Shows the raw lead record exactly as it would appear in a CRM — "
     "company, contact, source, territory."),
    ("2. Data Quality Check", "A hygiene pass over the record: flags missing critical fields "
     "and checks whether the company name looks like a near-duplicate of an existing account "
     "(e.g. \"Acme Inc\" vs \"Acme, Incorporated\"), the way a RevOps team would want caught "
     "before it pollutes the CRM."),
    ("3. Enrichment", "Adds firmographic context — industry type, employee count, current "
     "tech stack — from a mock data provider (or optionally a real lightweight web lookup)."),
    ("4. Scoring & Routing", "Blends a transparent rule-based score (firmographic fit, "
     "intent signals) with an AI-confidence read of the lead's free-text notes, then routes "
     "the lead to an Account Executive, an SDR, a nurture campaign, or flags it for a human "
     "to review — see \"Understanding routing outcomes\" below."),
    ("5. Marketing Campaign Enrollment", "Only appears for leads routed to nurture — shows "
     "the (simulated) enrollment into a marketing-platform campaign, closing the loop between "
     "sales and marketing instead of leaving a cold lead stranded."),
    ("6. Rep Brief", "An account summary, key buying signals, likely objections with "
     "suggested responses, and a recommended next action — the kind of prep a rep would "
     "otherwise spend 10-15 minutes assembling by hand."),
    ("7. Follow-up Email", "A draft outreach email tailored to the routing outcome (a "
     "consultative tone for AE-routed leads, a discovery tone for SDR-routed ones)."),
    ("8. Proposal / RFP Draft", "Only appears for formal RFP requests — a draft proposal "
     "assembled strictly from a library of pre-approved content blocks (never freely invented "
     "pricing or claims), always flagged for human review before it could ever be sent."),
    ("9. Telemetry Recorded", "The cycle time for this run versus an illustrative manual-"
     "process baseline, feeding the aggregate Metrics Dashboard."),
]
for name, desc in steps:
    with st.expander(name):
        st.write(desc)

st.info(
    "Step numbers sometimes skip (for example 4 straight to 6) — that's expected. Steps 5 "
    "and 8 are conditional and only appear for the scenarios they apply to."
)

st.header("Understanding routing outcomes")
c1, c2 = st.columns(2)
with c1:
    st.markdown(ui_theme.badge("Route to AE", "ae"), unsafe_allow_html=True)
    st.caption("High-scoring lead — ready for an Account Executive to engage directly.")
    st.markdown(ui_theme.badge("Route to SDR", "sdr"), unsafe_allow_html=True)
    st.caption("Mid-scoring lead — needs SDR discovery/qualification first.")
with c2:
    st.markdown(ui_theme.badge("Route to Nurture", "nurture"), unsafe_allow_html=True)
    st.caption("Lower-scoring or early-stage lead — enrolled in a nurture campaign instead.")
    st.markdown(ui_theme.badge("Needs Human Review", "review"), unsafe_allow_html=True)
    st.caption(
        "The rule-based score and the AI's read of the lead disagree by too much to trust "
        "automatically — this is a guardrail, not a failure. A human makes the final call."
    )

st.header("The 8 sample scenarios")
st.write("Each one is deliberately built to demonstrate a specific behavior:")
scenario_table = [
    {"Scenario": "1. Hot Enterprise — State University System", "Demonstrates": "Clean high-score path -> Route to AE"},
    {"Scenario": "2. Cold SMB — Tutoring Company", "Demonstrates": "Low-score path -> Nurture, plus a duplicate-company data-quality flag"},
    {"Scenario": "3. Formal RFP — Community College District", "Demonstrates": "The proposal-draft branch and the human-review gate"},
    {"Scenario": "4. Ambiguous Mid-Market", "Demonstrates": "Rule score and AI confidence deliberately disagree -> Needs Human Review"},
    {"Scenario": "5. Warm Mid-Market — K-12 District", "Demonstrates": "A boundary case between SDR and AE routing"},
    {"Scenario": "6. Out-of-Territory", "Demonstrates": "A disqualifying rule overriding an otherwise decent score"},
    {"Scenario": "7. Small Corporate-Training Buyer", "Demonstrates": "A straightforward SDR-tier lead"},
    {"Scenario": "8. Existing-Customer Upsell", "Demonstrates": "A special routing path for accounts that are already customers"},
]
st.dataframe(scenario_table, use_container_width=True, hide_index=True)

st.header("The other two pages")
with st.expander("Before vs After"):
    st.write(
        "Pick any scenario and see a side-by-side of the manual process a rep would follow "
        "today versus what the copilot just did automatically, plus the qualitative reasons "
        "this matters beyond raw time saved (consistency, always-on coverage, auditability)."
    )
with st.expander("Metrics Dashboard"):
    st.write(
        "Aggregate telemetry across every run you've triggered: total runs, automation "
        "success rate, average time saved, percentage needing human review, and an "
        "illustrative pipeline-velocity model that translates faster response time into "
        "revenue language. Use the \"Run all 8 sample leads\" button here to populate it "
        "quickly."
    )

st.header("Frequently asked questions")
with st.expander("Is any of this using real company data?"):
    st.write(
        "No. All 8 leads are fictional sample data designed to exercise specific behaviors. "
        "Salesforce, the marketing platforms, and firmographic enrichment are mocked "
        "interfaces — see the README's \"Swappable for production\" section for how each "
        "would connect to a real system."
    )
with st.expander("What's the difference between Mock and Live mode?"):
    st.write(
        "Mock mode uses deterministic templates for the rep brief, email, and proposal — "
        "free, instant, and identical every time. Live mode calls the real Anthropic API for "
        "those same three tasks. Everything else (scoring, routing, data quality) is "
        "deterministic in both modes so the demo stays predictable regardless of mode."
    )
with st.expander("Why does the proposal always say \"Needs Human Review\"?"):
    st.write(
        "By design. Proposals are unconditionally routed to human review in the code itself, "
        "regardless of how confident the generation was — this is a deliberate guardrail, not "
        "a bug, reflecting how proposal/pricing content should work in a real deployment."
    )
with st.expander("Can I add my own lead instead of the 8 samples?"):
    st.write(
        "Not in this UI — the 8 samples are intentionally fixed so every run is reproducible "
        "and demonstrates a specific, known behavior. The underlying `run_workflow(lead_id)` "
        "function in `revops_copilot/orchestration/workflow.py` would be the extension point "
        "for accepting arbitrary new leads."
    )
